Class {
	#name : 'FamixRepTestFileAnchor',
	#superclass : 'FamixRepTestEntity',
	#traits : 'FamixTFileNavigation',
	#classTraits : 'FamixTFileNavigation classTrait',
	#category : 'FamixReplication-Tests-TestModel',
	#package : 'FamixReplication-Tests',
	#tag : 'TestModel'
}

{ #category : 'meta' }
FamixRepTestFileAnchor class >> annotation [
	<FMClass: #FileAnchor super: #FamixRepTestEntity>
	<package: #'Famix-Replication-Tests'>
]
