Class {
	#name : 'FamixRepTestModel',
	#superclass : 'MooseModel',
	#category : 'FamixReplication-Tests-TestModel',
	#package : 'FamixReplication-Tests',
	#tag : 'TestModel'
}

{ #category : 'meta' }
FamixRepTestModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits')
]

{ #category : 'meta' }
FamixRepTestModel class >> annotation [
	<FMClass: #FamixRepTestModel super: #MooseModel>
	<package: #'Famix-Replication-Tests'>
	
]
