Class {
	#name : 'FamixRepTestSourceTextAnchor',
	#superclass : 'FamixRepTestEntity',
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : 'FamixReplication-Tests-TestModel',
	#package : 'FamixReplication-Tests',
	#tag : 'TestModel'
}

{ #category : 'meta' }
FamixRepTestSourceTextAnchor class >> annotation [
	<FMClass: #SourceTextAnchor super: #FamixRepTestEntity>
	<package: #'Famix-Replication-Tests'>
]
